export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f0f1f2',
        'surface-dim': '#d9dadb',
        'on-primary-fixed-variant': '#093cab',
        'primary-fixed-dim': '#b6c4ff',
        'on-tertiary-fixed-variant': '#852402',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#3056c4',
        'tertiary': '#591400',
        'surface-container-low': '#f3f4f5',
        'tertiary-container': '#802100',
        'on-primary-container': '#96adff',
        'surface-container-high': '#e7e8e9',
        'secondary-fixed': '#d1f041',
        'on-background': '#191c1d',
        'on-secondary-fixed-variant': '#3f4c00',
        'on-surface': '#191c1d',
        'on-primary': '#ffffff',
        'outline': '#747685',
        'on-secondary-fixed': '#181e00',
        'on-surface-variant': '#444653',
        'on-tertiary-container': '#ff9474',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'surface-container': '#edeeef',
        'primary': '#002576',
        'surface': '#f8f9fa',
        'on-secondary-container': '#596a00',
        'tertiary-fixed': '#ffdbd1',
        'secondary': '#556500',
        'tertiary-fixed-dim': '#ffb59f',
        'inverse-primary': '#b6c4ff',
        'surface-bright': '#f8f9fa',
        'secondary-container': '#ceed3e',
        'on-primary-fixed': '#00164f',
        'primary-container': '#0038a8',
        'on-secondary': '#ffffff',
        'surface-variant': '#e1e3e4',
        'primary-fixed': '#dce1ff',
        'inverse-surface': '#2e3132',
        'error-container': '#ffdad6',
        'background': '#f8f9fa',
        'outline-variant': '#c4c5d5',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#b5d321',
        'on-tertiary-fixed': '#3a0a00',
        'surface-container-highest': '#e1e3e4',
        'error': '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'gutter': '24px',
        'unit': '4px',
        'md': '24px',
        'sm': '16px',
        'xl': '64px',
        'lg': '40px',
        'xs': '8px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
      boxShadow: {
        'ambient': '0px 4px 12px rgba(0, 0, 0, 0.05)',
      },
      backgroundImage: {
        'hero-gradient': 'linear-gradient(rgba(0, 37, 118, 0.7), rgba(0, 37, 118, 0.7))',
      },
    },
  },
  plugins: [
    function ({ addComponents }) {
      addComponents({
        '.px-margin-mobile': {
          paddingLeft: '16px',
          paddingRight: '16px',
        },
        '.px-margin-desktop': {
          paddingLeft: '48px',
          paddingRight: '48px',
        },
        '@screen md': {
          '.px-margin-mobile': {
            paddingLeft: '48px',
            paddingRight: '48px',
          },
        },
      })
    },
  ],
}
